### ISSUE TITLE
Linker errors

### ISSUE THREAD

**Issue by VioletDarkKitty** [loathingKernel/pcsxr#6]
```/usr/bin/ld: CMakeFiles/pcsxr.dir/Cheat.c.o:(.bss+0x20): multiple definition of `cfgfile_basename'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/Cheat.c.o:(.bss+0x1020): multiple definition of `cfgfile'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x1000): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/ConfDlg.c.o:(.bss+0x7f160): multiple definition of `cfgfile_basename'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/ConfDlg.c.o:(.bss+0x80160): multiple definition of `cfgfile'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x1000): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/Config.c.o:(.bss+0x1000): multiple definition of `cfgfile'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x1000): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/Config.c.o:(.bss+0x0): multiple definition of `cfgfile_basename'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/DebugMemory.c.o:(.bss+0x0): multiple definition of `cfgfile_basename'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/DebugMemory.c.o:(.bss+0x1000): multiple definition of `cfgfile'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x1000): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/GtkGui.c.o:(.bss+0x20): multiple definition of `cfgfile_basename'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/GtkGui.c.o:(.bss+0x1020): multiple definition of `cfgfile'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x1000): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/LnxMain.c.o:(.bss+0x0): multiple definition of `cfgfile_basename'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/LnxMain.c.o:(.bss+0x1000): multiple definition of `cfgfile'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x1000): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/MemcardDlg.c.o:(.bss+0xce40): multiple definition of `cfgfile_basename'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/MemcardDlg.c.o:(.bss+0xde40): multiple definition of `cfgfile'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x1000): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/Plugin.c.o:(.bss+0x20): multiple definition of `cfgfile_basename'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/pcsxr.dir/Plugin.c.o:(.bss+0x1020): multiple definition of `cfgfile'; CMakeFiles/pcsxr.dir/AboutDlg.c.o:(.bss+0x1000): first defined here
```
On the fix-pango branch

**Comment by loathingKernel** [comment]
There is this [PR](https://github.com/iCatButler/pcsxr/pull/18) on the parent repository. I could cherry-pick it or you could build with clang or use `-Wno-odr` in the meantime.

**Comment by VioletDarkKitty** [comment]
Oh sorry, I didn't check every PR.
We should perhaps try to find a maintainer and merge everything...
