### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by Sebbyastian** [loathingKernel/pcsxr#8]
Disregard this. I am retarded 😂

**Comment by loathingKernel** [comment]
Hahaha, how are you? I have missed you. How is the quarantine treating you?

**Comment by Sebbyastian** [comment]
There is no quarantine in Soviet redbackistan. Only the illusion necessary to convince the public that they care, after they dropped the ball so spectacularly with the bushfires. That illusion lasts a few days for one or two states, then they decide whether it's necessary to continue. Politicians can still fly over the borders, though, with punishment akin to a slap on the wrist (something like "pay the state legal fees for this case and you're good to go"). Anyway, I was wrong to attribute this hilarious bug to you, since you forked this project (I didn't see that initially) and so the readme got forked with it. Peace out 👌✌️

**Comment by loathingKernel** [comment]
Given our past it would be a hilarious bug indeed. Have a nice day to you too :smiley: .
